---
language: python
dist: xenial
sudo: required
python: 3.6

before_install:
  - pip3 install omero-py
  - pip3 install flake8
  - pip3 install -U setuptools
  - flake8 .

script:
  - python3 setup.py test --pytest-args='-v -v'
  - python3 setup.py sdist install --record files.txt
  - python3 -c 'import omero.clients; import omero_marshal.encode'
  - cat files.txt | xargs rm -rf
  - python3 setup.py bdist_egg
  - easy_install dist/*.egg
  - python3 -c 'import omero.clients; import omero_marshal.encode'

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
