---
language: python
jobs:
    include:
        - name: "OMERO 5.2"
          env: OMERO_VERSION=5.2
          python: 2.7
          script: .travis/python2
        - name: "OMERO 5.3"
          env: OMERO_VERSION=5.3
          python: 2.7
          script: .travis/python2
        - name: "OMERO 5.4"
          env: OMERO_VERSION=5.4
          python: 2.7
          script: .travis/python2
        - name: "OMERO 5.5"
          env: OMERO_VERSION=5.5
          python: 2.7
          script: .travis/python2
        - name: "OMERO 5.6"
          env: OMERO_VERSION=5.6
          python: 3.6
          script: .travis/python3
