---
language: python
dist: xenial
# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
python: 3.6

env:
  matrix:
    - OMERO_VERSION=5.2
    - OMERO_VERSION=5.3
    - OMERO_VERSION=5.4
    - OMERO_VERSION=5.5

before_install:
  - pip3 install omero-py==5.6.dev9
  - pip3 install flake8
  - pip3 install -U setuptools
  - flake8 .

script:
  - python3 setup.py test --pytest-args='-v -v'
  - python3 setup.py sdist install --record files.txt
  - python3 -c 'import omero.clients; import omero_marshal.encode'
  - cat files.txt | xargs rm -rf
  - python3 setup.py bdist_egg
  - easy_install dist/*.egg
  - python3 -c 'import omero.clients; import omero_marshal.encode'
